version: "3.3"
services:
 nginx:
  build:
   context: .
   dockerfile: nginx/nginx.Dockerfile
  image: nginx
  ports:
   - 80:80
  links:
   - web
  volumes:
   - ./:/var/www/web  

 web:
  build:
   context: .
   dockerfile: web.Dockerfile
  volumes:
   - ./:/var/www/web
  links:
   - mysql

 mysql:
  image: mysql:5.7
  ports:
   - 33061:3306
  environment:
   - MYSQL_HOST=mysql
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=test_db
   - MYSQL_PORT=3306

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
   - PMA_HOST=mysql
   - PMA_USER=root
   - PMA_PASSWORD=root
  links:
   - mysql
  ports:
   - 8080:80
